# Generated by Django 5.2.6 on 2026-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population_density', models.IntegerField(help_text='People per sq km')),
                ('crime_rate', models.FloatField(help_text='Crime index (lower is better)')),
                ('green_space', models.FloatField(help_text='Percentage of green area')),
                ('schools', models.IntegerField(default=0)),
                ('hospitals', models.IntegerField(default=0)),
                ('restaurants', models.IntegerField(default=0)),
                ('malls', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
