# Generated by Django 5.2.6 on 2026-02-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='habitat',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='habitat',
            name='pollution_level',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
